### ISSUE TITLE
After entering credentials nothing happens

### ISSUE THREAD

**Issue by dinnouti** [mikiest/sptools#10]
I am having a little issue, after entering my authentication credentials nothing happens, it only creates a file inside of the project called spconfig.json. Is there a way to force refresh the files from SharePoint to show in VSC? Could it be that I am using SharePoint Online (O365)?

**Comment by mikiest** [comment]
Have you setup your `sptools.spFolders` correctly? This should be the list of folders SPTools will fetch for you. You can set this up in your user or workspace settings in VS Code.

**Comment by mikiest** [comment]
Closing as no update from op.
