### ISSUE TITLE
The server relative url is used to create the folder structure rather than the site relative url

### ISSUE THREAD

**Issue by ebbypeter** [mikiest/sptools#3]
If i use the site http://dev-space.contoso.com, the folder created is Projectname/SiteAssets/,
but if I use a site http://dev-space.contoso.com/sites/SiteColl1, the folder created is /sites/SiteColl1/Projectname/SiteAssets/ 

My user setting is like so
{
    "sptools.workFolder": "D:\OneDrive\Work\Dev\",
    "sptools.spFolders": [
        "/SiteAssets"
    ]
}

**Comment by mikiest** [comment]
Yes, this is correct and expected.

In the background, the extension is using mostly REST endpoints which require server relative paths.

I am open to changes though, if you can bring some valid arguments against that :)
