### ISSUE TITLE
Can SPTools:Sync be used to sync the files? Currently it is just download from site.

### ISSUE THREAD

**Issue by ebbypeter** [mikiest/sptools#4]

**Comment by mikiest** [comment]
There's probably a tiny confusion here, coming from (me) the extension itself though.

`SPTools: Sync` is actually a Download only command. It will be renamed in the next version.

To `Sync` the current file - meaning either uploading your local version or downloading the remote one depending on the modified dates - you have the option to click on the status bar icon (given that an update is required):

![image](https://cloud.githubusercontent.com/assets/15056200/11740219/f300ff6a-9fe8-11e5-8b47-61f0bf7d32b1.png)

At the moment this button is only useful when the remote file is more recent than the local one. I will change this soon so the button will trigger the relevant command whether the file needs to be downloaded or uploaded.

For now to just upload your local file, simply use the `Upload` command.
