### ISSUE TITLE
undefined ("workFolder" setting) does not exist.

### ISSUE THREAD

**Issue by leorente** [mikiest/sptools#5]
Receive this erro msg when create new workspace

![capture](https://cloud.githubusercontent.com/assets/283551/18885852/d0bc22e8-84c3-11e6-9dee-00f437ce3dad.PNG)

**Comment by mikiest** [comment]
Please provide the details below to help me investigate the issue:
- Where have you set the `sptools.workFolder` option on the screenshot? Is it in the workspace/user setting file?
- Which `OS` are you using?
- What is the `value` of the setting? For disclosure purpose, you can just write a similar path structure (e.g. \test\folder\) in reply.

As a side note, the warning message you can see allows you to create the non-existing folder in the target site by clicking on `Create`. The value of the path seems to be unresolved in your case though.

**Comment by ravenboilinux** [comment]
I am having the same issue has leorente is having. I just install Visual Studio Code and the SPTools today. When I try to create a new workspace i get this error. I am using the default setting, not overriding with the my workspace/user setting file. The OS is window 7. 
![image](https://cloud.githubusercontent.com/assets/4099274/19053481/25b67f5e-8989-11e6-9ddf-8b5288b67b2c.png)

**Comment by mikiest** [comment]
@leorente @ravenboilinux Thanks for the feedback.

**The latest version I just published should fix the issue** - which was due to outdated contribution endpoints being used. Just update the extension through VS Code.
