### ISSUE TITLE
Unable to Authenticate to SharePoint Online

### ISSUE THREAD

**Issue by ravenboilinux** [mikiest/sptools#6]
We use Okta/adfs to authenticate to o365 but when I try to login to throu SPTools i get 
![image](https://cloud.githubusercontent.com/assets/4099274/19167115/47f3024e-8bd8-11e6-8937-364c983bb990.png)

**Comment by mikiest** [comment]
Makes sense, as I haven't had the opportunity to try it using ADFS yet.

I'll see if I can setup something and debug. As this may take long, it would be great if you (or someone who is already setup with ADFS) could clone this project, debug it and give me the feedback here (or even make a pull request with the fix).

I'll keep you posted.

**Comment by mikiest** [comment]
I just tried to login on a **ADFS** enabled environment (no Okta) and it worked just fine.

Looking back into the actual [code throwing this specific error](https://github.com/mikiest/sptools/blob/master/spcore.ts#L118), it looks like your credentials are being rejected: this error is displayed when the response is `401 Unauthorized`.

Can you please confirm if the credentials you are using are working through another tool? Can you also make sure the credentials are entered in the correct format?

**Comment by ShauneDonohue** [comment]
When I try and run SPTools: New workspace it prompts me for project name, URL, and credentials. After a few seconds I get a "Warn  File not Found." message.   I do not have time right now to debug the problem right now but if I do I will let you know.

**Comment by mikiest** [comment]
@ravenboilinux closing as no reply. Feel free to reopen with further comments.
