### ISSUE TITLE
Creating a new Workspace with SharePoint Online error with File Not Found" message

### ISSUE THREAD

**Issue by ShauneDonohue** [mikiest/sptools#7]
When I try and run SPTools: New workspace on O365 it prompts me for project name, URL, and credentials. After a few seconds I get a "Warn File not Found." message. I do not have time right now to debug the problem right now but if I do I will let you know.

**Comment by mikiest** [comment]
This is typically due to the folders not being configured correctly. Please check in your user/workspace settings that the folders you are trying to fetch from SharePoint are correct and existing on the remote site.

**Comment by ShauneDonohue** [comment]
you were correct the "Style Library/en-us/Themable/test" folder did not exist.  Once I added this folder the project was created.  A nice option would be for it to create that SPTool project in the current folder structure instead of creating a new one.
now when I add a file to one of the folders I get a warn  The file /_catalogs/masterpage/test/js/test.js does not exist.

**Comment by ShauneDonohue** [comment]
As a follow up to my last comment, I figured out how to get around this, if you first add the file to the SharePoint list you will no longer get this error.  So to summarize when you add a new file to a project you must manually upload the file then the SPTool upload process will work.
