### ISSUE TITLE
No File/Folder creation?

### ISSUE THREAD

**Issue by clechner77** [mikiest/sptools#9]
Wondering if I'm doing something incorrectly or that's just part of how SPTools works at the moment (no file/folder creation).  Essentially, I/we have to have the files/folders already created in Sharepoint (doc library, etc) then SPTools becomes useful, correct?  If not then apparently I'm missing something, because when I create a new file and attempt an SPTools upload with a new file, it stalls on "Checking File State."

**Comment by mikiest** [comment]
You are doing nothing wrong, this is a current limitation. Files/folders have to be created on the remote site first.
I will tackle this as a priority (alternatively I'm open to pull requests!), but the next release is not scheduled yet.
